### ISSUE TITLE
Why are there restrictions on the election timeout, heartbeat and lease?

### ISSUE THREAD

**Issue by bubbajoe** [jmsadair/raft#80]
Hello,

I came across this repo and the simplicity/flexibility really inspired me to switch from [hashicorp/raft](https://github.com/hashicorp/raft) in my Distributed API Gateway at [dgate-io/dgate](https://github.com/dgate-io/dgate); There were a few other reasons, but I will spare you the details.

I plan to create a cluster that spans across the globe (I am aware of the potential low latency/throughput). And I am wondering why there are min/max restrictions on the `election timeout`, `heartbeat` and `lease` values and if there are any potential issues that you foresee if they were to be increased.

These values seem very low even for a regional deployment of some key/value database.

**Comment by jmsadair** [comment]
Hi Joe,

I don't think there are issues with this for your use case. I chose values that I thought were within a reasonable range for most use cases, but I can go ahead and increase them or remove them all together. I'll update this today or tomorrow.
