### ISSUE TITLE
Add support for advertised addresses

### ISSUE THREAD

**Issue by bubbajoe** [jmsadair/raft#85]
This implementation assumes that the address that is being listened on (e.g. 0.0.0.0:1234), is the same address that other nodes will use to connect. This is usually the case for testing locally, but in staging/production, it's common to use domain names, and/or different addresses.

I don't think there is much to change except removing the address comparison [here](https://github.com/jmsadair/raft/blob/8a0bfebc7d0cb813849bc240a942c42c16e574cb/raft.go#L381)

To get around this, I am manually adding Transport and using the advertised address as the address variable for the `NewRaft` function.

**Comment by jmsadair** [comment]
Apologies for the delay in getting to this. This seems simple enough - to be clear, you would like to be able to bootstrap a node with a configuration that contains a differing address than the address the node is initialized with?

For example, let's say that that we initialize a node using the `NewRaft` function with ID `n` and address `127.0.0.1`. You would like the ability to call `Bootstrap` on this node with a configuration containing an ID-address pair such as `(n, 127.0.0.2)`. Is that right?

**Comment by bubbajoe** [comment]
Yep, basically 2 different addresses. Listen Address (which could be `0.0.0.0:1234`) and Advertised Address (which could be `node1.domain.top:4321`).

Advertised Address should always default to the Listen Address.

**Comment by jmsadair** [comment]
Great. In the future, feel free to make pull requests yourself - you don't have to, but I occasionally get caught up with work or other stuff and it may take me a while to get to it. If it's a simple change like this and you put up a PR, I'll make sure to review it in a timely manner.
